[build]
  functions = "functions"
  publish = "public"

[[redirects]]
  from = "/old-path"
  to = "/new-path"
  status = 301
  force = true

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"

[[edge_functions]]
  name = "hello"
  path = "/hello"
  file = "edge-functions/hello.js"
